### ISSUE TITLE
unit conversion improvement

### ISSUE THREAD

**Issue by jeras** [j123b567/scpi-parser#62] opened 2015-10-16 14:06 UTC
Currently unit conversion allows only multiplication.

Temperature units would require a linear conversion, so a multiplication and an addition.

Logarithmic units often used for signal power in spectrum analyzers would require logarithmic operations.

**Comment by j123b567** [comment] 2015-10-16 14:13
This issue is partial duplicate of #26 so I will move further conversation there.

**Closed by j123b567** 2015-10-16 14:13 UTC
Labels: duplicate
